language: c
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env: BUILDTYPE=Debug
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      env: BUILDTYPE=Release
    - os: linux
      dist: xenial
      sudo: required
      compiler: clang
      env: BUILDTYPE=Debug
    - os: linux
      dist: xenial
      sudo: required
      compiler: clang
      env: BUILDTYPE=Release
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          update: true
          packages:
            - musl-tools
      env: BUILDTYPE=Debug MY_CC=musl-gcc MY_LINK=musl-gcc
    - os: osx
      osx_image: xcode9.3
      env: BUILDTYPE=Debug
    - os: osx
      osx_image: xcode9.3
      env: BUILDTYPE=Release
before_install:
  - umask 022
  - test -n $MY_CC  && export CC=$MY_CC
  - test -n $MY_CXX  && export CXX=$MY_CXX
  - test -n $MY_LINK  && export LINK=$MY_LINK
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew upgrade python; fi
script: make && make test
branches:
  only:
    - master
